// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $api_telegram_webhook from './routes/api/telegram/webhook.ts'
import * as $index from './routes/index.tsx'
import * as $lastfm_webhook from './routes/lastfm/webhook.tsx'
import * as $Counter from './islands/Counter.tsx'
import * as $WebView from './islands/WebView.tsx'
import type { Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/api/telegram/webhook.ts': $api_telegram_webhook,
    './routes/index.tsx': $index,
    './routes/lastfm/webhook.tsx': $lastfm_webhook,
  },
  islands: {
    './islands/Counter.tsx': $Counter,
    './islands/WebView.tsx': $WebView,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
